// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjvOUeaQpCy1dFMkfq9Ei7zcReMPph_Uk',
    appId: '1:738508310831:web:0f7be6287b991621b579da',
    messagingSenderId: '738508310831',
    projectId: 'emailnnotification',
    authDomain: 'emailnnotification.firebaseapp.com',
    storageBucket: 'emailnnotification.firebasestorage.app',
    measurementId: 'G-F5S6P03FY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm7gO6bZRT27e_731pqQzm0ztmHT4rReI',
    appId: '1:738508310831:android:20ae635eb3da30a9b579da',
    messagingSenderId: '738508310831',
    projectId: 'emailnnotification',
    storageBucket: 'emailnnotification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApVvxxNXfm7ZO_v88qPjtuQLvaxVgYra8',
    appId: '1:738508310831:ios:f2209133ec70c3fcb579da',
    messagingSenderId: '738508310831',
    projectId: 'emailnnotification',
    storageBucket: 'emailnnotification.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApVvxxNXfm7ZO_v88qPjtuQLvaxVgYra8',
    appId: '1:738508310831:ios:f2209133ec70c3fcb579da',
    messagingSenderId: '738508310831',
    projectId: 'emailnnotification',
    storageBucket: 'emailnnotification.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjvOUeaQpCy1dFMkfq9Ei7zcReMPph_Uk',
    appId: '1:738508310831:web:73257da4781e7aadb579da',
    messagingSenderId: '738508310831',
    projectId: 'emailnnotification',
    authDomain: 'emailnnotification.firebaseapp.com',
    storageBucket: 'emailnnotification.firebasestorage.app',
    measurementId: 'G-6HJM4B8YDD',
  );
}
